# docker-compose build
# docker-compose up -d
# http://localhost:21337/top.html
# http://localhost:21337/db
# http://localhost:21337/kekka
# docker-compose down

version: '3'

services:
  cnpg:
    build: pg
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    ports:
      - "25432:5432"
#    volumes:
#      - ./pg/data:/var/lib/postgresql/data
  cnnd:
    build: nd
    ports:
      - "21337:80"
